repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.0.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [] # optional: list of Conventional Commits types to allow
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    # -   id: cargo-check
    # -   id: clippy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: check-merge-conflict
    - id: debug-statements
    - id: check-case-conflict
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace

ci:
  skip: [fmt]
