on:
  workflow_dispatch:
    inputs:
      releaseLevel:
        required: false
        description: 'Release level'
        default: 'alpha'

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_RELEASE_VERSION: 0.16.2

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Cache cargo-release
        id: cache-cargo-bin-cargo-release
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cargo-bin-cargo-release-${{ env.CARGO_RELEASE_VERSION }}
          path: ~/.cargo/bin/cargo-release

      - name: Install cargo-release
        if: steps.cache-cargo-bin-cargo-release.outputs.cache-hit != 'true'
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-release
          version: ${{ env.CARGO_RELEASE_VERSION }}
          
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
           git config user.name "GitHub Actions"
           git config user.email "example@example.com"
           cargo release --skip-push --token ${{ secrets.CRATES_IO_TOKEN }} --no-confirm -- ${{ github.event.inputs.releaseLevel }}
           git changed >> History.md
          COMMIT_MESSAGE: 'chore: create release'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'example@example.com'
          PR_BRANCH_NAME: 'chore-create-release-${PR_ID}'
          PR_TITLE: 'chore: create release'
