on:
  workflow_dispatch:
    inputs:
      releaseLevel:
        required: false
        description: 'Release level'
        default: 'alpha'

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_RELEASE_VERSION: 0.16.2

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          
      - run: sudo apt install sponge

      - name: Cache cargo-release
        id: cache-cargo-bin-cargo-release
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cargo-bin-cargo-release-${{ env.CARGO_RELEASE_VERSION }}
          path: ~/.cargo/bin/cargo-release

      - name: Install cargo-release
        if: steps.cache-cargo-bin-cargo-release.outputs.cache-hit != 'true'
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-release
          version: ${{ env.CARGO_RELEASE_VERSION }}
      - run: cargo install jilu --git https://github.com/rustic-games/jilu
      - run: git config user.name "GitHub actions"
      - run: git config user.email "me+bot@mause.me"
      - run: git checkout main
      - run: jilu | sponge CHANGELOG.md
      - run: git add CHANGELOG.md
      - run: 'git commit -m "chore: Update changelog" || echo "No changes to commit"'
      - run: cargo release --skip-push --token ${{ secrets.CRATES_IO_TOKEN }} --no-confirm -- ${{ github.event.inputs.releaseLevel }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3

      # - run: git push --tags

      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Mock Proxy
          column-name: In progress
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
