jobs:
  release:
  - steps:
    - uses: actions/checkout@v1
    - run: cargo login ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - run: cargo release alpha
